# name: "Website"

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1

#     - name: Set up Python 3.7
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.7

#     - name: Install sarkas and its dependencies
#       run: |
#         pip install -e .

#     - name: Make docs
#       run: |
#         cd docs
#         make html
#     # Create an artifact of the html output.
#     - uses: actions/upload-artifact@v1
#       with:
#         name: DocumentationHTML
#         path: docs/_build/html/

#     # Publish built docs to gh-pages branch.
#     # https://github.com/peaceiris/actions-gh-pages
#     - name: Deploy Website and Docs
#       if: success() && github.ref == 'refs/heads/main'
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         publish_branch: gh-pages
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: docs/_build/html/
